{% set version = "1.13.2" %}

package:
  name: omcompiler
  version: {{ version }}

source:
  # use git because no tarball including submodules is available
  git_url: https://github.com/OpenModelica/OMCompiler.git
  git_tag: v{{ version }}

build:
  number: 3
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - autoconf
    - automake
    - libtool
    - pkg-config
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - bdw-gc
    - expat
    - lp_solve
    - openjdk
    - openblas
  run:
    - bdw-gc
    - expat
    - lp_solve
    - openjdk
    - openblas
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - zip

test:
  requires:
    - git
    - pyfmi
  commands:
    - omc --version
    - cd /tmp && git clone https://github.com/openturns/otfmi.git && cd otfmi && ./mo2fmu.sh ./otfmi/example/file/deviation.mo /tmp/deviation.fmu
    - python -c "import pyfmi; model = pyfmi.load_fmu('/tmp/deviation.fmu'); res = model.simulate(); print([(x, res[x][0]) for x in res.keys()])"

about:
   home: https://openmodelica.org/
   license: OSMC-PL
   license_family: GPL
   license_file: OSMC-License.txt
   summary: The Open Source Modelica Suite - OpenModelica Compiler

extra:
  recipe-maintainers:
    - jschueller
