{% set version = "1.21.0" %}

package:
  name: omcompiler
  version: {{ version }}

source:
  # use git because no tarball including submodules is available
  git_url: https://github.com/OpenModelica/OpenModelica.git
  git_tag: v{{ version }}

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - autoconf
    - automake
    - make
    - libtool
    - pkg-config
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - expat
    - lp_solve
    - libblas
    - liblapack
    - libcurl
    - boost-cpp
  run:
    - expat
    - lp_solve
    - {{ compiler('c') }}
    - zip

test:
  commands:
    - omc --version

about:
   home: https://openmodelica.org/
   license: OSMC-PL
   license_family: GPL
   license_file: OSMC-License.txt
   summary: The Open Source Modelica Suite - OpenModelica Compiler

extra:
  recipe-maintainers:
    - jschueller
