{% set version = "1.23.1" %}

package:
  name: omcompiler
  version: {{ version }}

source:
  # use git because no tarball including submodules is available
  git_url: https://github.com/OpenModelica/OpenModelica.git
  git_tag: v{{ version }}
  patches:
    # om_pm_model.cpp:272:33: error: variable 'std::ifstream f_s' has initializer but incomplete type
    - fstream.patch

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - ninja
    - pkg-config
    - autoconf
    - automake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - {{ compiler('fortran') }}
  host:
    - openjdk
    - libblas
    - liblapack
    - libcurl
    - libboost-devel
    - libiconv
    - libuuid
  run:
    - openjdk
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - zip

test:
  source_files:
    - OMCompiler/Examples/Circle.mo
  commands:
    - omc --version
    - echo 'loadFile("OMCompiler/Examples/Circle.mo"); getErrorString(); buildModelFMU(Circle); getErrorString();' > export.mos
    - omc export.mos
    - ls Circle.fmu
    - echo 'loadFile("OMCompiler/Examples/Circle.mo"); getErrorString(); buildModelFMU(Circle, platforms={"dynamic"}); getErrorString();' > export.mos
    - omc --fmuCMakeBuild=true --fmuRuntimeDepends=modelica export.mos
    - ls Circle.fmu

about:
   home: https://openmodelica.org/
   license: OSMC-PL
   license_family: GPL
   license_file: OSMC-License.txt
   summary: The Open Source Modelica Suite - OpenModelica Compiler

extra:
  recipe-maintainers:
    - jschueller
