{% set version = "1.21.0" %}

package:
  name: omcompiler
  version: {{ version }}

source:
  # use git because no tarball including submodules is available
  git_url: https://github.com/OpenModelica/OpenModelica.git
  git_tag: v{{ version }}

build:
  number: 1
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - autoconf
    - automake
    - make
    - libtool
    - pkg-config
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - openjdk
    - libblas
    - liblapack
    - libcurl
    - boost-cpp
  run:
    - openjdk
    - make
    - {{ compiler('c') }}
    - zip

test:
  requires:
    - curl
  commands:
    - omc --version
    - curl -LO https://github.com/OpenModelica/OpenModelica/raw/v{{ version }}/OMCompiler/Examples/Circle.mo
    - echo 'loadFile("Circle.mo"); getErrorString(); buildModelFMU(Circle); getErrorString();' > export.mos
    - omc export.mos
    - ls Circle.fmu

about:
   home: https://openmodelica.org/
   license: OSMC-PL
   license_family: GPL
   license_file: OSMC-License.txt
   summary: The Open Source Modelica Suite - OpenModelica Compiler

extra:
  recipe-maintainers:
    - jschueller
