{% set version = "1.16.5" %}

package:
  name: omcompiler
  version: {{ version }}

source:
  # use git because no tarball including submodules is available
  git_url: https://github.com/OpenModelica/OpenModelica.git
  git_tag: v{{ version }}

build:
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - cmake
    - autoconf
    - automake
    - libtool
    - pkg-config
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - expat
    - lp_solve
    - openjdk
    - liblapack
    - libcurl
  run:
    - expat
    - lp_solve
    - openjdk
    - {{ compiler('c') }}
    - zip

test:
  requires:
    - pyfmi
  commands:
    - omc --version
    - cd /tmp && curl -fsSO https://raw.githubusercontent.com/openturns/otfmi/master/mo2fmu.sh && sh mo2fmu.sh ${PREFIX}/share/doc/omc/testmodels/BouncingBall.mo
    - python -c "import pyfmi; model = pyfmi.load_fmu('/tmp/BouncingBall.fmu'); res = model.simulate(); print([(v, res[v][-1]) for v in res.keys()])"

about:
   home: https://openmodelica.org/
   license: OSMC-PL
   license_family: GPL
   license_file: OSMC-License.txt
   summary: The Open Source Modelica Suite - OpenModelica Compiler

extra:
  recipe-maintainers:
    - jschueller
