context:
  version: "1.26.3"

package:
  name: omcompiler
  version: ${{ version }}

source:
  # use git because no tarball including submodules is available
  git: https://github.com/OpenModelica/OpenModelica.git
  tag: v${{ version }}
  submodules: false
  patches:
    # prefer pthreads-win32 over PThreads4W
    - threads.patch
    # error C1083: Cannot open include file: 'omc_inline.h': No such file or directory
    - gc.patch

build:
  number: 0
  skip:
    - osx

requirements:
  build:
    - cmake
    - ninja
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}
    - ${{ compiler('fortran') }}
    - if: unix
      then:
       - pkg-config
       - autoconf
       - automake
       - make
  host:
    - openjdk
    - libblas
    - liblapack
    - libcurl
    - libboost-devel
    - libiconv
    - if: win
      then:
        - pthreads-win32
        - libintl-devel
  run:
    - openjdk
    - cmake
    - make
    - zip
    - ${{ stdlib('c') }}
    - ${{ compiler('c') }}
    - ${{ compiler('cxx') }}

tests:
  - script:
      - omc --version
      - echo 'loadFile("OMCompiler/Examples/Circle.mo"); getErrorString(); buildModelFMU(Circle); getErrorString();' > export.mos
      - omc export.mos
      - ls Circle.fmu
      - echo 'loadFile("OMCompiler/Examples/Circle.mo"); getErrorString(); buildModelFMU(Circle, platforms={"dynamic"}); getErrorString();' > export.mos
      - omc --fmuCMakeBuild=true --fmuRuntimeDepends=modelica export.mos
      - ls Circle.fmu
    files:
      source:
        - OMCompiler/Examples/Circle.mo

about:
   homepage: https://openmodelica.org/
   license: LicenseRef-OSMC-PL
   license_family: GPL
   license_file: OSMC-License.txt
   summary: The Open Source Modelica Suite - OpenModelica Compiler

extra:
  recipe-maintainers:
    - jschueller
