travis:
  secure:
    BINSTAR_TOKEN: Ry+o8wsk5PniRYqzol2Xu7BXniNa5BBZaBkNupMhCqOY0mdVN07OiwRZqore7rpWcOjwIiB4WBNaMdeWKzbV4ilMvBZ6xs4c8+t5VFsYHYRbZrYmyqkta9mguLpam8P1Ifv5MQSumj2VOP6926bibZpkNbbWbGgri6/VP2EH8FXIxTnc/FY5/CTsWxkhRkq+UxFi7lXGRNp7IZ98x/Lggifduv9ImBZVlpIceBcHBGKlVKjeC4w1CI+RFMfNeUVLutK/k1g/Qw0XEAr1JaKTBMu/OQo77ZAfsq3LXc11+VaQuzQRITuKCytoknBukjq95RSyMDDsg1RqC4H1rVdA3OUX5oUw4uBO05YWayclmyuIDHs8fdjEAiksp/MxoX6bgVnamzCZdZZF9GAACIqgX6haZPOsqgtTIZ+0VfrN+KDcWhtZ+tBiQkGgfqs/SJpVwdRwcABbXxoDrc1FZwoLtm/ZhpfKx7aHTSQjWKNH4mLjrPm7OCDEQrbzyBKsXBCcgSrgoCGSvxyMy+5M00nR6I641gNgtedrc8PVB+4VQJOUcMiZcVaZ14wgIzKZWc55QNjFg+bM+65fUX8hfJj1f710avOm1LFwOlFr8LlVZqNZEh+8b8MyHgqF1Yswt/Xgg9Jx1TK87BRNXrvcyZ3IlGMs1iTuS/TRvbTwXBXi+dQ=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
